### This file creates the file for highlighting the sequences for the adc selection app for the segmentation -> used for concepts

# BERNER

- setz up selectin app
- read manual selecetion by hakim 
- check if all 297 hav an according adc
- save df

In [49]:
import sys
sys.path.append("/home/bule/berner_daten_analyse")

# quickhack -> move this file to the locatoin wher you want the processed niftis to be stored

In [50]:
import json
import os
import pandas as pd
from utils.dcm2niix import *
from utils.selection import *

from datetime import datetime

BERN_PATH='/nasdata/Berner_Daten/Other_Side_Bilddaten'

In [51]:
# for app selection 
DATA_DIR = "/nasdata/Berner_Daten/Other_Side_Bilddaten"  # <------ Path to the RAW data
PROJECT_DIR = "/home/bule/berner_daten_analyse"          # <------ Path to the project directory
DATA_PATH='/home/bule/berner_daten_analyse/data'
APP_DATA_PATH='/home/bule/berner_daten_analyse/apps/app_manual_preselection/selection_adc_3quartal2025'

# finaly used patients
df_selection=pd.read_csv(os.path.join(DATA_PATH,'clinical','baseline_bern_test_impute_10n.csv'))
df_selection.info()

# all selected sequences
df_no_ = pd.read_csv(os.path.join(PROJECT_DIR,'data','dwi_t1_df_merged.csv'))
df_no_
print(len(set(df_no_['Patient_ID'])))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   p_id                     297 non-null    float64
 1   age                      297 non-null    float64
 2   sex                      297 non-null    int64
 3   nihss                    297 non-null    int64
 4   selbststaendig           297 non-null    int64
 5   prehypert                297 non-null    int64
 6   systol                   297 non-null    int64
 7   toast                    297 non-null    int64
 8   mrs                      297 non-null    float64
 9   MED_prestatin            297 non-null    float64
 10  MED_Parenteral           297 non-null    float64
 11  MED_Dabigatran_Pradaxa   297 non-null    float64
 12  MED_Rivaroxaban_Xarelto  297 non-null    float64
 13  MED_Vit_K_ag             297 non-null    float64
 14  MED_Ticagrelor           297 non-null    float64
 15  MED_Clopidogrel          297 non-null    float64
 16  mrs_unfavorable          297 non-null    int64
 17  p_idx                    297 non-null    int64
dtypes: float64(10), int64(8)
memory usage: 41.9 KB
430

In [52]:
only_2_df

,Patient_ID,Study_ID,Sequence_ID,Full_Path_Nifti,join_crit,Path_Nifti,Modality,Date,Shape
0,76813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000076813/20170614_4361718/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2017-06-14,"(128, 128, 25, 2)"
1,76813,20170929_4371316,t1_se_tra__1.3.12.2.1107.5.2.41.169589.2017092...,/home/bule/berner_daten_analyse/data/nifti/000...,/0000076813/20170929_4371316/t1_se_tra__1.3.12...,/home/bule/berner_daten_analyse/data/nifti/000...,anatomic,2017-09-29,"(600, 640, 29)"
2,442968,20151109_3835318,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,/home/bule/berner_daten_analyse/data/nifti/000...,/0000442968/20151109_3835318/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2015-11-09,"(192, 192, 19, 2)"
3,442968,20151110_3835468,t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201...,/home/bule/berner_daten_analyse/data/nifti/000...,/0000442968/20151110_3835468/t1_se_r_tra_KM__1...,/home/bule/berner_daten_analyse/data/nifti/000...,anatomic,2015-11-10,"(224, 256, 24)"
4,481858,20121025_3013771,resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000481858/20121025_3013771/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2012-10-25,"(176, 176, 20, 2)"
...,...,...,...,...,...,...,...,...,...
845,82364672,20170113_4216439,t1_fl2d_tra__1.3.12.2.1107.5.2.36.40186.201701...,/home/bule/berner_daten_analyse/data/nifti/008...,/0082364672/20170113_4216439/t1_fl2d_tra__1.3....,/home/bule/berner_daten_analyse/data/nifti/008...,anatomic,2017-01-13,"(336, 384, 24)"
846,82395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082395993/20170802_4406866/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2017-08-02,"(128, 128, 25, 2)"
847,82395993,20170802_4406866,t1_fl2d_tra__1.3.12.2.1107.5.2.36.40270.201708...,/home/bule/berner_daten_analyse/data/nifti/008...,/0082395993/20170802_4406866/t1_fl2d_tra__1.3....,/home/bule/berner_daten_analyse/data/nifti/008...,anatomic,2017-08-02,"(324, 384, 24)"
848,82789223,20161003_4120929,resolve_3scan_trace_tra_p3_160_TRACEW__1.3.12....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082789223/20161003_4120929/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2016-10-03,"(160, 160, 30, 2)"
849,82789223,20160521_4001514,t1_se_r_tra_KM__1.3.12.2.1107.5.2.30.27272.201...,/home/bule/berner_daten_analyse/data/nifti/008...,/0082789223/20160521_4001514/t1_se_r_tra_KM__1...,/home/bule/berner_daten_analyse/data/nifti/008...,anatomic,2016-05-21,"(224, 256, 24)"

In [53]:
df_no_['p_id_float'] = df_no_['Patient_ID'].astype(float)
df_no_subsel=df_no_[df_no_['p_id_float'].isin(df_selection['p_id'].astype(float))]

only_2_df=pd.read_csv('/home/bule/berner_daten_analyse/data/only_2_df.csv')
only_2_df_selection = only_2_df[only_2_df['Patient_ID'].isin(df_selection['p_id'].astype(float))]
only_2_df_selection_dwi= only_2_df_selection[only_2_df_selection['Modality']=='dwi']
# uncomment to save the file for adc selection app
# only_2_df_selection_dwi.merge(df_no_subsel, on=["Patient_ID","Sequence_ID","Study_ID","Modality","Date"], how="left").to_csv(os.path.join(DATA_PATH,"dwi_t1_df_merged_selection_for_adc2.csv", index=False))
only_2_df_selection_dwi

,Patient_ID,Study_ID,Sequence_ID,Full_Path_Nifti,join_crit,Path_Nifti,Modality,Date,Shape
0,76813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000076813/20170614_4361718/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2017-06-14,"(128, 128, 25, 2)"
2,442968,20151109_3835318,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,/home/bule/berner_daten_analyse/data/nifti/000...,/0000442968/20151109_3835318/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2015-11-09,"(192, 192, 19, 2)"
4,481858,20121025_3013771,resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000481858/20121025_3013771/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2012-10-25,"(176, 176, 20, 2)"
8,653853,20161216_4193466,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000653853/20161216_4193466/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2016-12-16,"(128, 128, 25, 2)"
12,768081,20130110_3061277,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/000...,/0000768081/20130110_3061277/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/000...,dwi,2013-01-10,"(128, 128, 25, 2)"
...,...,...,...,...,...,...,...,...,...
826,14150158,20170626_4372408,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/001...,/0014150158/20170626_4372408/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/001...,dwi,2017-06-26,"(128, 128, 25, 2)"
832,14239248,20170809_4413689,ep2d_diff_4scan_trace_p2_s2_inkl.Neckcoil_TRAC...,/home/bule/berner_daten_analyse/data/nifti/001...,/0014239248/20170809_4413689/ep2d_diff_4scan_t...,/home/bule/berner_daten_analyse/data/nifti/001...,dwi,2017-08-09,"(384, 384, 30, 2)"
840,82298262,20161224_4200830,ep2d_diff_3scan_trace_p2__1.3.12.2.1107.5.2.30...,/home/bule/berner_daten_analyse/data/nifti/008...,/0082298262/20161224_4200830/ep2d_diff_3scan_t...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2016-12-24,"(192, 192, 19, 2)"
844,82364672,20170112_4215453,resolve_3scan_trace_tra_176_p2_TRACEW__1.3.12....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082364672/20170112_4215453/resolve_3scan_tra...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2017-01-12,"(176, 176, 20, 2)"
846,82395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN__1.3.12.2.1107.5.2....,/home/bule/berner_daten_analyse/data/nifti/008...,/0082395993/20170802_4406866/ep2d_diff_M128_b0...,/home/bule/berner_daten_analyse/data/nifti/008...,dwi,2017-08-02,"(128, 128, 25, 2)"

## Selection with app (apps/app_manual_preselection/0_1_adc_app.py)

In [5]:
folds_id_tab = pd.read_csv(os.path.join(DATA_PATH,"clinical/10Fold_ids_test.csv"))

## Martin

In [6]:

file_path =os.path.join(APP_DATA_PATH,"Martin_sequences.json")

with open(file_path, "r") as f:
    selection_martin_dict = json.load(f)

rows = []
for patid, selection_dict in selection_martin_dict.items():
    for modality, sequences in selection_dict.items():
        for sequence in sequences:
            study_id, sequence_id = sequence.split('/')
            rows.append({
                'Patient_ID': patid,
                'Study_ID': study_id,
                'Sequence_ID': sequence_id,
                'Modality': modality,
                'Labeller': 'Martin'  
            })
selection_martin_df = pd.DataFrame(rows).drop_duplicates()
selection_martin_df['Sequence_path']=selection_martin_df.apply(lambda x: os.path.join(BERN_PATH,x['Patient_ID'],x['Study_ID'],x['Sequence_ID']),axis=1)
selection_martin_df['Date'] = selection_martin_df['Study_ID'].str[:8].apply(lambda x: datetime.strptime(x, '%Y%m%d').strftime('%Y-%m-%d'))

In [7]:
selection_martin_df

,Patient_ID,Study_ID,Sequence_ID,Modality,Labeller,Sequence_path,Date
0,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2017-06-14
1,0000442968,20151109_3835318,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2015-11-09
2,0000481858,20121025_3013771,resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2012-10-25
3,0000653853,20161216_4193466,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2016-12-16
4,0000801402,20161123_4171427,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2016-11-23
...,...,...,...,...,...,...,...
293,0014150158,20170626_4372408,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/001...,2017-06-26
294,0014239248,20170809_4413689,ep2d_diff_4scan_trace_p2_s2_inkl.Neckcoil_ADC_...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/001...,2017-08-09
295,0082298262,20161224_4200830,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2016-12-24
296,0082364672,20170112_4215453,resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2017-01-12
297,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2017-08-02

In [8]:
selection_martin_df["pi_d_float"] = selection_martin_df["Patient_ID"].astype(float)
pids_missing = folds_id_tab.loc[~folds_id_tab["p_id"].isin(selection_martin_df["pi_d_float"]), "p_id"]
pids_missing

Series([], Name: p_id, dtype: float64)

In [9]:
mask = selection_martin_df['Sequence_ID'].str.lower().str.contains("neckcoil|neck|coil")

inds = selection_martin_df.index[mask]
inds

Index([294], dtype='int64')

In [10]:
selection_martin_df.iloc[294]

Patient_ID                                              0082298262
Study_ID                                          20161224_4200830
Sequence_ID      ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....
Modality                                                     other
Labeller                                                    Martin
Sequence_path    /nasdata/Berner_Daten/Other_Side_Bilddaten/008...
Date                                                    2016-12-24
pi_d_float                                              82298262.0
Name: 295, dtype: object

## Hakim

## Merge

In [54]:
merge_selection=selection_martin_df

In [55]:
merge_selection

,Patient_ID,Study_ID,Sequence_ID,Modality,Labeller,Sequence_path,Date,pi_d_float
0,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2017-06-14,76813.0
1,0000442968,20151109_3835318,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2015-11-09,442968.0
2,0000481858,20121025_3013771,resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2012-10-25,481858.0
3,0000653853,20161216_4193466,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2016-12-16,653853.0
4,0000801402,20161123_4171427,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,2016-11-23,801402.0
...,...,...,...,...,...,...,...,...
293,0014150158,20170626_4372408,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/001...,2017-06-26,14150158.0
294,0014239248,20170809_4413689,ep2d_diff_4scan_trace_p2_s2_inkl.Neckcoil_ADC_...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/001...,2017-08-09,14239248.0
295,0082298262,20161224_4200830,ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2016-12-24,82298262.0
296,0082364672,20170112_4215453,resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1...,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2017-01-12,82364672.0
297,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,other,Martin,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,2017-08-02,82395993.0

## converzt to nifti

In [12]:
adc_df = []  # 
for _, row in merge_selection.iterrows():
    for dcm_ending in os.listdir(row['Sequence_path']):        
        adc_df.append({
            'Patient_ID': row['Patient_ID'],
            'Study_ID': row['Study_ID'],
            'Sequence_ID': row['Sequence_ID'],
            'File_Name': dcm_ending,
            'Full_Path': os.path.join(row['Sequence_path'], dcm_ending),
            'Modality': row['Modality'].upper()
        })

adc_df = pd.DataFrame(adc_df)
adc_df['Date'] = adc_df['Study_ID'].str[:8].apply(lambda x: datetime.strptime(x, '%Y%m%d').strftime('%Y-%m-%d'))
adc_df['Sequence_ID_split'] = adc_df['Sequence_ID'].apply(lambda x: split_at_anynumber_seq(x))

adc_df["File_Number"] = adc_df["File_Name"].str.extract(r'(\d+)').astype(int)
adc_df.sort_values(["Patient_ID", "Modality", "File_Number"], inplace=True)
adc_df.drop(columns=["File_Number"], inplace=True)
adc_df.reset_index()
# adc_df.to_csv(os.path.join(DATA_PATH, 'adc_df.csv'), index=False)

,index,Patient_ID,Study_ID,Sequence_ID,File_Name,Full_Path,Modality,Date,Sequence_ID_split
0,0,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,1.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
1,11,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,2.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
2,18,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,3.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
3,19,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,4.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
4,20,0000076813,20170614_4361718,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,5.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/000...,OTHER,2017-06-14,ep2d_diff_M128_b0_1000_DIN_ADC
...,...,...,...,...,...,...,...,...,...
6389,6382,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,21.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6390,6383,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,22.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6391,6384,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,23.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6392,6385,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,24.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC
6393,6386,0082395993,20170802_4406866,ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107....,25.dcm,/nasdata/Berner_Daten/Other_Side_Bilddaten/008...,OTHER,2017-08-02,ep2d_diff_M128_b0_1000_DIN_ADC

In [13]:
# Project data path
DATA_PATH='/home/bule/berner_daten_analyse/data'
NII_TARGET_PATH = '/home/bule/berner_daten_analyse/data/nifti'
LOG_PATH = os.path.join(NII_TARGET_PATH, 'conversion_errors_selection.log')

adc_df.sort_values(by='Patient_ID',inplace=True)
adc_df.head()
print(len(adc_df))

adc_df.groupby('Patient_ID').nunique().head()

6394

,Study_ID,Sequence_ID,File_Name,Full_Path,Modality,Date,Sequence_ID_split
Patient_ID,,,,,,,
0000076813,1,1,25,25,1,1,1
0000442968,1,1,19,19,1,1,1
0000481858,1,1,20,20,1,1,1
0000653853,1,1,25,25,1,1,1
0000768081,1,1,25,25,1,1,1

In [14]:
adc_df = adc_df[adc_df['Modality']=='OTHER']
source_dcm_sequences = [os.path.join('/',*path.split('/')[:-1]) for path in adc_df['Full_Path']]
source_dcm_sequences = list(set([os.path.join('/',path) for path in source_dcm_sequences]))
print(source_dcm_sequences[0])
target_nii_sequences= [os.path.join(*path.split('/')[4:]) for path in source_dcm_sequences]
target_nii_sequences_adc= [os.path.join(NII_TARGET_PATH,path) for path in target_nii_sequences]
print(target_nii_sequences_adc[0])

/nasdata/Berner_Daten/Other_Side_Bilddaten/0011706376/20130728_3197703/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013072816373534516771210.0.0.0
/home/bule/berner_daten_analyse/data/nifti/0011706376/20130728_3197703/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013072816373534516771210.0.0.0

In [15]:
LOG_PATH

'/home/bule/berner_daten_analyse/data/nifti/conversion_errors_selection.log'

In [ ]:
process_niftis=False
if process_niftis:
    process_directories(source_dcm_sequences, target_nii_sequences,log_path=LOG_PATH)# ~ 11 mins

Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 21 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 21 DICOM as 0011706376/20130728_3197703/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013072816373534516771210.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013072816373534516771210.0.0.0_ep2d_diff_3scan_trace_p2_20130728163615_3 (192x192x21x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "0011706376/20130728_3197703/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013072816373534516771210.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2013072816373534516771210.0.0.0_ep2d_diff_3scan_trace_p2_20130728163615_3.nii"
Conversion required 0.071833 seconds (0.023553 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0011706376/20130728_3197703/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013072816373534516771210.0.0.0 -> 0011706376/20130728_3197703/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013072816373534516771210.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 19 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 19 DICOM as 0011172207/20120901_2979181/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012090111283262973615372.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012090111283262973615372.0.0.0_ep2d_diff_3scan_trace_p2_20120901112701_3 (192x192x19x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "0011172207/20120901_2979181/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012090111283262973615372.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012090111283262973615372.0.0.0_ep2d_diff_3scan_trace_p2_20120901112701_3.nii"
Conversion required 0.098616 seconds (0.040669 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0011172207/20120901_2979181/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012090111283262973615372.0.0.0 -> 0011172207/20120901_2979181/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012090111283262973615372.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 19 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 19 DICOM as 0011250836/20121019_3010341/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012101914370825017561687.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012101914370825017561687.0.0.0_ep2d_diff_3scan_trace_p2_20121019143542_3 (192x192x19x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "0011250836/20121019_3010341/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012101914370825017561687.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012101914370825017561687.0.0.0_ep2d_diff_3scan_trace_p2_20121019143542_3.nii"
Conversion required 0.118827 seconds (0.038608 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0011250836/20121019_3010341/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012101914370825017561687.0.0.0 -> 0011250836/20121019_3010341/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012101914370825017561687.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 19 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 19 DICOM as 0013101560/20161023_4141024/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016102312161647428531336.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016102312161647428531336.0.0.0_ep2d_diff_3scan_trace_p2_20161023121456_3 (192x192x19x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "0013101560/20161023_4141024/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016102312161647428531336.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2016102312161647428531336.0.0.0_ep2d_diff_3scan_trace_p2_20161023121456_3.nii"
Conversion required 0.081410 seconds (0.030892 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0013101560/20161023_4141024/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016102312161647428531336.0.0.0 -> 0013101560/20161023_4141024/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016102312161647428531336.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 19 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 19 DICOM as 0010998993/20120529_2918983/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012052912153936483324010.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012052912153936483324010.0.0.0_ep2d_diff_3scan_trace_p2_20120529121403_3 (192x192x19x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "0010998993/20120529_2918983/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012052912153936483324010.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012052912153936483324010.0.0.0_ep2d_diff_3scan_trace_p2_20120529121403_3.nii"
Conversion required 0.087721 seconds (0.038032 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0010998993/20120529_2918983/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012052912153936483324010.0.0.0 -> 0010998993/20120529_2918983/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012052912153936483324010.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 25 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 25 DICOM as 0007450338/20140422_3389822/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014042210281133398736013.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2014042210281133398736013.0.0.0_ep2d_diff_M128_b0_1000_DIN_20140422102530_3 (128x128x25x1)
Compress: "/usr/bin/pigz" -n -f -6 "0007450338/20140422_3389822/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014042210281133398736013.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2014042210281133398736013.0.0.0_ep2d_diff_M128_b0_1000_DIN_20140422102530_3.nii"
Conversion required 0.070077 seconds (0.038000 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0007450338/20140422_3389822/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014042210281133398736013.0.0.0 -> 0007450338/20140422_3389822/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014042210281133398736013.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 25 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 25 DICOM as 0002081504/20130209_3082905/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013020908431267698107879.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2013020908431267698107879.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130209084131_3 (128x128x25x1)
Compress: "/usr/bin/pigz" -n -f -6 "0002081504/20130209_3082905/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013020908431267698107879.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2013020908431267698107879.0.0.0_ep2d_diff_M128_b0_1000_DIN_20130209084131_3.nii"
Conversion required 0.075205 seconds (0.042882 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0002081504/20130209_3082905/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013020908431267698107879.0.0.0 -> 0002081504/20130209_3082905/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013020908431267698107879.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 20 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Warning: Volume 0 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 20 DICOM as 0013273060/20160310_3938991/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2016031013202229746056619.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2016031013202229746056619.0.0.0_resolve_3scan_trace_tra_176_p2_20160310131853_3 (176x176x20x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "0013273060/20160310_3938991/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2016031013202229746056619.0.0.0/resolve_3scan_trace_tra_176_p2_ADC_1.3.12.2.1107.5.2.18.41437.2016031013202229746056619.0.0.0_resolve_3scan_trace_tra_176_p2_20160310131853_3.nii"
Conversion required 0.081750 seconds (0.030470 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0013273060/20160310_3938991/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2016031013202229746056619.0.0.0 -> 0013273060/20160310_3938991/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2016031013202229746056619.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 25 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 25 DICOM as 0013667530/20161015_4133876/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016101512420225146148629.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2016101512420225146148629.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161015124007_3 (128x128x25x1)
Compress: "/usr/bin/pigz" -n -f -6 "0013667530/20161015_4133876/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016101512420225146148629.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2016101512420225146148629.0.0.0_ep2d_diff_M128_b0_1000_DIN_20161015124007_3.nii"
Conversion required 0.069413 seconds (0.035220 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0013667530/20161015_4133876/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016101512420225146148629.0.0.0 -> 0013667530/20161015_4133876/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016101512420225146148629.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 30 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Warning: Volume 0 appears to be derived image ADC/Isotropic (non-zero b-value with zero vector length)
Convert 30 DICOM as 0003410390/20170418_4309773/ep2d_diff_tra_resolve_ADC__1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0/ep2d_diff_tra_resolve_ADC_1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0_ep2d_diff_tra_resolve_20170418071959_8 (160x160x30x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "0003410390/20170418_4309773/ep2d_diff_tra_resolve_ADC__1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0/ep2d_diff_tra_resolve_ADC_1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0_ep2d_diff_tra_resolve_20170418071959_8.nii"
Conversion required 0.101330 seconds (0.048280 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0003410390/20170418_4309773/ep2d_diff_tra_resolve_ADC__1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0 -> 0003410390/20170418_4309773/ep2d_diff_tra_resolve_ADC__1.3.12.2.1107.5.2.18.41102.2017041807294828614202566.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 21 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 21 DICOM as 0007855230/20150722_3744655/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015072212292398101937912.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015072212292398101937912.0.0.0_ep2d_diff_3scan_trace_p2_20150722122748_3 (192x192x21x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "0007855230/20150722_3744655/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015072212292398101937912.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015072212292398101937912.0.0.0_ep2d_diff_3scan_trace_p2_20150722122748_3.nii"
Conversion required 0.111092 seconds (0.040781 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0007855230/20150722_3744655/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015072212292398101937912.0.0.0 -> 0007855230/20150722_3744655/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015072212292398101937912.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 20 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 20 DICOM as 0006291732/20150428_3673947/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2015042816144022787350101.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.2015042816144022787350101.0.0.0_ep2d_diff_M128_b0_1000_DIN_20150428160550_3 (128x128x20x1)
Compress: "/usr/bin/pigz" -n -f -6 "0006291732/20150428_3673947/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2015042816144022787350101.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.2015042816144022787350101.0.0.0_ep2d_diff_M128_b0_1000_DIN_20150428160550_3.nii"
Conversion required 0.068113 seconds (0.037609 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0006291732/20150428_3673947/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2015042816144022787350101.0.0.0 -> 0006291732/20150428_3673947/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2015042816144022787350101.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 25 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 25 DICOM as 0011900440/20131202_3285963/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013120208213449117107845.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2013120208213449117107845.0.0.0_ep2d_diff_M128_b0_1000_DIN_20131202081721_3 (128x128x25x1)
Compress: "/usr/bin/pigz" -n -f -6 "0011900440/20131202_3285963/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013120208213449117107845.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2013120208213449117107845.0.0.0_ep2d_diff_M128_b0_1000_DIN_20131202081721_3.nii"
Conversion required 0.064827 seconds (0.033406 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0011900440/20131202_3285963/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013120208213449117107845.0.0.0 -> 0011900440/20131202_3285963/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013120208213449117107845.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 19 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 19 DICOM as 0010875379/20120229_2864618/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012022900363493159322845.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012022900363493159322845.0.0.0_ep2d_diff_3scan_trace_p2_20120229003517_3 (192x192x19x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "0010875379/20120229_2864618/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012022900363493159322845.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2012022900363493159322845.0.0.0_ep2d_diff_3scan_trace_p2_20120229003517_3.nii"
Conversion required 0.079257 seconds (0.029922 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0010875379/20120229_2864618/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012022900363493159322845.0.0.0 -> 0010875379/20120229_2864618/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012022900363493159322845.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 19 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 19 DICOM as 0013110888/20151212_3863535/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015121217555739532840884.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015121217555739532840884.0.0.0_ep2d_diff_3scan_trace_p2_20151212175423_3 (192x192x19x1)
Compress: "/usr/bin/pigz" -b 960 -n -f -6 "0013110888/20151212_3863535/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015121217555739532840884.0.0.0/ep2d_diff_3scan_trace_p2_ADC_1.3.12.2.1107.5.2.30.27272.2015121217555739532840884.0.0.0_ep2d_diff_3scan_trace_p2_20151212175423_3.nii"
Conversion required 0.096369 seconds (0.031452 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0013110888/20151212_3863535/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015121217555739532840884.0.0.0 -> 0013110888/20151212_3863535/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015121217555739532840884.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 25 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 25 DICOM as 0012781541/20150526_3696011/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015052615191539489540002.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2015052615191539489540002.0.0.0_ep2d_diff_M128_b0_1000_DIN_20150526151714_3 (128x128x25x1)
Compress: "/usr/bin/pigz" -n -f -6 "0012781541/20150526_3696011/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015052615191539489540002.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2015052615191539489540002.0.0.0_ep2d_diff_M128_b0_1000_DIN_20150526151714_3.nii"
Conversion required 0.073094 seconds (0.041794 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0012781541/20150526_3696011/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015052615191539489540002.0.0.0 -> 0012781541/20150526_3696011/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015052615191539489540002.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 25 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 25 DICOM as 0003938921/20141229_3578338/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014122912054939880982670.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2014122912054939880982670.0.0.0_ep2d_diff_M128_b0_1000_DIN_20141229120415_3 (128x128x25x1)
Compress: "/usr/bin/pigz" -n -f -6 "0003938921/20141229_3578338/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014122912054939880982670.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40270.2014122912054939880982670.0.0.0_ep2d_diff_M128_b0_1000_DIN_20141229120415_3.nii"
Conversion required 0.074890 seconds (0.041434 for core code).
Converted: /nasdata/Berner_Daten/Other_Side_Bilddaten/0003938921/20141229_3578338/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014122912054939880982670.0.0.0 -> 0003938921/20141229_3578338/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014122912054939880982670.0.0.0
Chris Rorden's dcm2niiX version v1.0.20220720  (JP2:OpenJPEG) GCC13.2.0 x86-64 (64-bit Linux)
Found 20 DICOM file(s)
Warning: This diffusion series does not have a B0 (reference) volume
Convert 20 DICOM as 0002910306/20151002_3804610/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2015100214524256289676687.0.0.0/ep2d_diff_M128_b0_1000_DIN_ADC_1.3.12.2.1107.5.2.36.40186.2015100214524256289676687.0.0.0_ep2d_diff_M128_b0_1000_DIN_20151002145051_3 (128x128x20x1)

## prepare df for lesion segmentation

In [58]:
target_nii_sequences_adc

['/home/bule/berner_daten_analyse/data/nifti/0012360058/20150605_3705553/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2015060512504127330243902.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0001397044/20161019_4137895/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2016101916162136923847281.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012001929/20140205_3333214/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014020523002351426533375.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0006640419/20160607_4016423/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016060715424852095436604.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0009152121/20161216_4193320/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016121610574435567022144.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013393600/20160518_3998111/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2016051808225787030910830.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0082298262/20161224_4200830/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016122419201234282384844.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0008631417/20160616_4024891/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016061613020337576253064.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013283065/20160317_3944938/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2016031709015937067620790.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0000076813/20170614_4361718/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2017061416530865378251256.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0003608484/20140512_3405403/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014051211573594926734243.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0006593860/20131113_3272791/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.201311131037005125732859.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0008887349/20170220_4253770/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017022023144140236994732.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0010532480/20140920_3502620/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.201409201552387579224459.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011245964/20121018_3009163/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012101811284876678014482.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011926716/20131217_3297630/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.201312171415429500812047.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011300299/20121116_3028799/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2012111613391136096467183.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0001120794/20170116_4218415/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017011615131252371173003.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013164171/20160114_3888741/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2016011408422394680007345.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0008205540/20160614_4022058/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016061406295297827501339.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0008862320/20170612_4358424/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017061210303122050330944.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013570617/20160819_4081661/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.201608192201555574977349.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011102713/20120723_2953348/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012072301372161361301341.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0001494589/20130322_3111977/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013032210132943978517524.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013045423/20151107_3833879/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015110717004494035227813.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0002081504/20130209_3082905/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013020908431267698107879.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0000911666/20170318_4279828/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017031803434419578756163.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012787388/20150530_3699765/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015053021241621000997629.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012638900/20150301_3626748/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015030101541623980646752.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013250558/20160301_3930264/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016030116515490319838509.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013582569/20160826_4087721/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2016082612261345449642580.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012524182/20150112_3587862/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015011215404114490871420.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011480130/20130313_3105661/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013031316375863430376956.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011597844/20130528_3155306/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2013052816210431886355126.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011094761/20120711_2946362/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012071111105341560067360.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0006924433/20160328_3953388/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016032809270691296404001.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011420316/20130204_3078550/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013020411064122454430395.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012870480/20150715_3739282/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2015071517302852321687772.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0007176473/20150705_3729899/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015070508351454623703013.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0014150158/20170626_4372408/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2017062610344421737363773.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0002457849/20130515_3146971/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013051516054152085162548.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012730360/20150425_3671675/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015042515322287583149929.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0000830267/20140331_3374880/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.20140331175722548233096.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013639013/20160928_4118945/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016092819163958935826817.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012090484/20150903_3780360/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015090321095745987268968.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011737328/20130818_3211640/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013081806581426018001342.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013036904/20151101_3828095/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015110119072781449026443.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0005768640/20150416_3663784/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015041607244246524101339.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011900440/20131202_3285963/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013120208213449117107845.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0002074265/20161010_4129033/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016101019451235014919207.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0010449574/20120409_2888846/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012040914565533551145414.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0004207793/20120625_2935678/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012062512113425313637504.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011423250/20130206_3080737/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013020614512020222904208.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013045270/20151107_3833739/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2015110705285926751001335.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0004327233/20140226_3348945/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014022608483383466829030.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0010822127/20120121_2840853/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012012117112951416072165.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0004524152/20150815_3764238/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015081513043289756871481.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012263877/20140716_3454338/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.201407161354076644458627.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0005771439/20160523_4003187/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016052319545847754233624.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013110888/20151212_3863535/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015121217555739532840884.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0009157646/20131022_3257263/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013102220135264655603624.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012731510/20150426_3671883/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015042612544574850342484.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0002920026/20140906_3491955/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014090611542476372629471.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011911239/20131206_3289860/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013120601141641734623352.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013017152/20151017_3816432/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015101723393844339265263.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013982095/20170401_4293517/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017040120033418406712910.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011301546/20121118_3029395/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012111819264021884444774.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0000442968/20151109_3835318/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2015110920165992102092193.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011979461/20140122_3321890/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014012221000712908512673.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011357428/20121222_3052849/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2012122213291045397701374.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0009030565/20141217_3571378/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014121715462276268235148.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0010905243/20170213_4246588/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017021320224924940556603.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0009046542/20120519_2913511/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012051918354095522787613.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011706376/20130728_3197703/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013072816373534516771210.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0000996254/20130724_3195639/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013072421213631171336905.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0007815360/20140614_3430160/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014061410232886392209257.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012662542/20150315_3638989/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2015031511370822812481699.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013169807/20160118_3892589/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016011820000210635897340.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011293764/20130708_3183238/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013070810395476199318553.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0014095556/20170527_4344905/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2017052721300555034740587.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0004751884/20160825_4085988/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016082505265456580980765.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0004769619/20160325_3952357/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016032507024493479801339.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0001063871/20131017_3253819/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2013101716025958261111549.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012891096/20150728_3749782/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.201507282051056461212528.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0003921980/20150914_3788235/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2015091408351292124006031.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0004117115/20170401_4293389/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2017040112372828604745793.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013105663/20151208_3860103/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015120819281435262084705.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0003173844/20160402_3958496/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016040222091875073098679.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0001357840/20170130_4232882/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2017013022185215800701374.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0010583335/20140219_3344266/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014021921264272346644172.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0000653853/20161216_4193466/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2016121611003455620544484.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011850701/20131031_3264403/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2013103118111789352283304.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012873870/20150717_3741110/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40186.2015071714094897961545459.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0003448606/20130110_3061202/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013011009232939183613212.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012882640/20150723_3745336/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015072309371093575514666.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011069368/20120629_2939441/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012062920264377595808813.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012060321/20140312_3359814/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014031206275067859701341.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0003477711/20170122_4224418/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2017012212195017665583461.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012747050/20150505_3679991/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.2015050515593013112083753.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013193678/20160131_3903986/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016013113565558907819929.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0001870394/20131101_3264798/resolve_3scan_trace_tra_176_p2_ADC__1.3.12.2.1107.5.2.18.41437.201311011136166347629831.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0002923041/20170703_4379063/Diffusion_tra_3mm_ADC__1.3.12.2.1107.5.2.18.141120.2017070310463983789143341.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011671726/20130709_3184770/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.20130709174046873517569.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013951904/20170316_4277925/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2017031611533657689638546.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0014023970/20170425_4314113/Diffusion_tra_3mm_ADC__1.3.12.2.1107.5.2.18.141120.2017042516083826040890116.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0002500051/20141017_3523243/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014101718255361825673353.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0007450338/20140422_3389822/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014042210281133398736013.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013623915/20160921_4111453/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2016092115190540339651804.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0003733009/20170517_4335633/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.201705171015585790213561.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011090715/20120710_2945814/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2012071017233125762260920.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012268143/20140719_3456662/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014071912475426527921346.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012781541/20150526_3696011/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2015052615191539489540002.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0005060311/20140819_3478008/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.2014081910564285595050403.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0002663120/20120316_2875713/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2012031616580116588125438.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0010977813/20120510_2908761/ep2d_diff_M128_b0_1000_DIN_ADC__1.3.12.2.1107.5.2.36.40270.201205101945208731417565.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013222651/20160215_3916655/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016021511052412918692975.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0013430394/20160605_4014116/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016060521284776257736691.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0008794286/20161021_4140588/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2016102122302512443593475.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012455350/20141107_3539878/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.201411072023564616515100.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0011756977/20130901_3221412/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2013090113583491109817545.0.0.0',
 '/home/bule/berner_daten_analyse/data/nifti/0012445266/20141101_3534110/ep2d_diff_3scan_trace_p2_ADC__1.3.12.2.1107.5.2.30.27272.2014110110232153536713978.0.0.0',

In [ ]:
df=pd.read_csv(os.path.join(ANALYSIS_PATH, 'only_2_df.csv'))# each patietn has 2 nfitis

In [57]:
# check for duplicated  select all created niftis -> some didnt work
data=[]
for path in all_niftis:
    patient_id = int(path.split("/")[6])
    study_id = path.split("/")[7]
    sequence_id = path.split("/")[8]
    full_path = path
    data.append({'Patient_ID':patient_id, 'Study_ID':study_id,'Sequence_ID':sequence_id ,'Full_Path_Nifti':full_path})
    
nii_df=pd.DataFrame(data)
nii_df['join_crit']=[ os.path.join('/',*path.split('/')[6:-1]) for path in nii_df['Full_Path_Nifti']]
nii_df=nii_df.merge(df_modality, on='join_crit', how='left')

# len(nii_df[['Sequence_ID','Study_ID']].unique()) 
duplicates = nii_df[nii_df.duplicated(subset=['Study_ID', 'Sequence_ID'], keep=False)]
print(duplicates.head(1))

nii_df.drop_duplicates(subset=['Sequence_ID'], keep='first', inplace=True)
nii_df.info()

NameError: name 'all_niftis' is not defined